//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pipo_Pipon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Comida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comida()
        {
            this.OrdenDetalles = new HashSet<OrdenDetalle>();
        }
    
        public int itemId { get; set; }
        [DisplayName("Nombre")]
        public string comidaNombre { get; set; }
        [DisplayName("Precio")]
        public decimal comidaPrecio { get; set; }
        [DisplayName("Cantidad")]
        public Nullable<int> cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenDetalle> OrdenDetalles { get; set; }
    }
}
