//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pipo_Pipon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OrdenDetalle
    {
        public int ordenDetalles { get; set; }
        [DisplayName("Nombre Cliente")]
        public string nombreCliente { get; set; }
        [DisplayName("Comida")]
        public int itemId { get; set; }
        [DisplayName("Bebida")]
        public int bebidaId { get; set; }
        [DisplayName("Descuento")]
        public decimal unitPrice { get; set; }
        [DisplayName("Total")]
        public decimal total { get; set; }
    
        public virtual Bebida Bebida { get; set; }
        public virtual Comida Comida { get; set; }
    }
}
